### ISSUE TITLE
Android音频暂停好像没有反应

### ISSUE THREAD

**Issue by KnnethKong** [wanliyang1990/wlmedia#1]
Android音频暂停好像没有反应

**Comment by wanliyang1990** [comment]
具体是怎样的情况，是用项目自带的例子也不能暂停吗？

**Comment by KnnethKong** [comment]
自带的音频使用wlMedia.setSource("http://zhugeqilv.oss-cn-beijing.aliyuncs.com/audio/customer/201902/27/i_1551233661(null).wav");

**Comment by wanliyang1990** [comment]
好的 已经知道问题了 后面我改一下

**Comment by KnnethKong** [comment]
谢谢

**Comment by wanliyang1990** [comment]
问题已经解决了 你再试试呢

**Comment by KnnethKong** [comment]
谢谢
