### ISSUE TITLE
播放音频的时候，报这个错，崩溃退出了，麻烦看下这个啥问题？

### ISSUE THREAD

**Issue by hanxiaofeng** [wanliyang1990/wlmedia#13]
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): weak global reference table overflow (max=51200)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115] weak global reference table dump:
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 51200):
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51199: 0x12de7640 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51198: 0x12de75e0 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51197: 0x12de7520 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51196: 0x12de74c0 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51195: 0x12de7400 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51194: 0x12dd9e20 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51193: 0x12dd9ac0 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51192: 0x12dd9a60 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51191: 0x12dd99a0 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]     51190: 0x12dd97c0 java.lang.Thread
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of com.ywl5320.wlmedia.WlMedia
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of com.example.helloworld.AudioPlayWidgetLayout
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of com.example.helloworld.AudioPlayWidgetLayout$2
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of androidx.appcompat.widget.AppCompatImageView
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]      4341 of java.lang.Class (4341 unique instances)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.ThreadGroup (2 unique instances)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (144 elements)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (576 elements)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         3 of byte[] (5184 elements) (3 unique instances)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (9216 elements)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of byte[] (40000 elements)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.view.View$PerformClick
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.view.ViewRootImpl$ViewRootHandler
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]         1 of com.android.internal.os.ZygoteInit$MethodAndArgsCaller
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115]       226 of java.lang.Thread (226 unique instances)
12-05 10:22:39.788 4009-4152/com.example.helloworld A/art: art/runtime/indirect_reference_table.cc:115] 
12-05 10:22:40.039 4009-4152/com.example.helloworld A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
12-05 10:22:40.039 4009-4152/com.example.helloworld A/art: art/runtime/runtime.cc:366] Runtime aborting --- recursively, so no thread-specific detail!
12-05 10:22:40.039 4009-4152/com.example.helloworld A/art: art/runtime/runtime.cc:366] 
    
    --------- beginning of crash
12-05 10:22:40.039 4009-4152/com.example.helloworld A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4152 (Thread-55449)
12-05 10:22:40.092 245-245/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-05 10:22:40.092 245-245/? A/DEBUG: Build fingerprint: 'Android/rk3368_64/rk3368:6.0.1/MXC89L/builder10151223:user/release-keys'
12-05 10:22:40.092 245-245/? A/DEBUG: Revision: '0'
12-05 10:22:40.092 245-245/? A/DEBUG: ABI: 'arm64'
12-05 10:22:40.092 245-245/? A/DEBUG: pid: 4009, tid: 4152, name: Thread-55449  >>> com.example.helloworld <<<
12-05 10:22:40.092 245-245/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-05 10:22:40.128 245-245/? A/DEBUG: Abort message: 'art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): weak global reference table overflow (max=51200)'
12-05 10:22:40.128 245-245/? A/DEBUG:     x0   0000000000000000  x1   0000000000001038  x2   0000000000000006  x3   0000000000000000
12-05 10:22:40.128 245-245/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
12-05 10:22:40.128 245-245/? A/DEBUG:     x8   0000000000000083  x9   00000076467f2a70  x10  0000000000000003  x11  00000000000001e0
12-05 10:22:40.128 245-245/? A/DEBUG:     x12  00000055b6115890  x13  00000055b51a9000  x14  0000000000000000  x15  0000000000000000
12-05 10:22:40.128 245-245/? A/DEBUG:     x16  00000076467eb6a0  x17  00000076467ad8dc  x18  c000000000000000  x19  000000762b9b3510
12-05 10:22:40.129 245-245/? A/DEBUG:     x20  000000762b9b3450  x21  0000000000000002  x22  0000000000000006  x23  0000007643613000
12-05 10:22:40.129 245-245/? A/DEBUG:     x24  00000055b60c03a0  x25  00000055b614b140  x26  00000055b51ba7a0  x27  0000007643536000
12-05 10:22:40.129 245-245/? A/DEBUG:     x28  00000055b6184b60  x29  000000762b9b24e0  x30  00000076467ab078
12-05 10:22:40.129 245-245/? A/DEBUG:     sp   000000762b9b24e0  pc   00000076467ad8e4  pstate 0000000020000000
12-05 10:22:40.153 245-245/? A/DEBUG: backtrace:
12-05 10:22:40.153 245-245/? A/DEBUG:     #00 pc 000000000006a8e4  /system/lib64/libc.so (tgkill+8)
12-05 10:22:40.153 245-245/? A/DEBUG:     #01 pc 0000000000068074  /system/lib64/libc.so (pthread_kill+68)
12-05 10:22:40.153 245-245/? A/DEBUG:     #02 pc 0000000000020e08  /system/lib64/libc.so (raise+28)
12-05 10:22:40.153 245-245/? A/DEBUG:     #03 pc 000000000001b5a8  /system/lib64/libc.so (abort+60)
12-05 10:22:40.153 245-245/? A/DEBUG:     #04 pc 0000000000432568  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+324)
12-05 10:22:40.153 245-245/? A/DEBUG:     #05 pc 0000000000137224  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
12-05 10:22:40.153 245-245/? A/DEBUG:     #06 pc 0000000000131cc8  /system/lib64/libart.so (_ZN3art7BarrierD2Ev+296)
12-05 10:22:40.153 245-245/? A/DEBUG:     #07 pc 0000000000469154  /system/lib64/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+212)
12-05 10:22:40.153 245-245/? A/DEBUG:     #08 pc 0000000000432650  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+556)
12-05 10:22:40.154 245-245/? A/DEBUG:     #09 pc 0000000000137224  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+3136)
12-05 10:22:40.154 245-245/? A/DEBUG:     #10 pc 00000000002724c8  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+372)
12-05 10:22:40.154 245-245/? A/DEBUG:     #11 pc 00000000003094e0  /system/lib64/libart.so (_ZN3art9JavaVMExt16AddWeakGlobalRefEPNS_6ThreadEPNS_6mirror6ObjectE+68)
12-05 10:22:40.154 245-245/? A/DEBUG:     #12 pc 000000000035e1ec  /system/lib64/libart.so (_ZN3art3JNI16NewWeakGlobalRefEP7_JNIEnvP8_jobject+320)
12-05 10:22:40.154 245-245/? A/DEBUG:     #13 pc 0000000000151470  /system/lib64/libart.so (_ZN3art8CheckJNI6NewRefEPKcP7_JNIEnvP8_jobjectNS_15IndirectRefKindE+704)
12-05 10:22:40.154 245-245/? A/DEBUG:     #14 pc 00000000003245f0  /system/lib64/libart.so (_ZN3art14ObjectRegistry11InternalAddINS_6mirror6ObjectEEEmNS_6HandleIT_EE+880)
12-05 10:22:40.154 245-245/? A/DEBUG:     #15 pc 00000000003248f0  /system/lib64/libart.so (_ZN3art14ObjectRegistry3AddEPNS_6mirror6ObjectE+128)
12-05 10:22:40.154 245-245/? A/DEBUG:     #16 pc 00000000001aeb80  /system/lib64/libart.so (_ZN3art3Dbg11GetThreadIdEPNS_6ThreadE+364)
12-05 10:22:40.154 245-245/? A/DEBUG:     #17 pc 0000000000313d88  /system/lib64/libart.so (_ZN3art4JDWP9JdwpState16PostThreadChangeEPNS_6ThreadEb+696)
12-05 10:22:40.154 245-245/? A/DEBUG:     #18 pc 00000000001acd18  /system/lib64/libart.so (_ZN3art3Dbg15PostThreadStartEPNS_6ThreadE+44)
12-05 10:22:40.154 245-245/? A/DEBUG:     #19 pc 000000000045d2a0  /system/lib64/libart.so (_ZN3art6Thread6AttachEPKcbP8_jobjectb+748)
12-05 10:22:40.154 245-245/? A/DEBUG:     #20 pc 000000000042efb4  /system/lib64/libart.so (_ZN3art7Runtime19AttachCurrentThreadEPKcbP8_jobjectb+24)
12-05 10:22:40.154 245-245/? A/DEBUG:     #21 pc 000000000030a1c4  /system/lib64/libart.so (_ZN3art3JII19AttachCurrentThreadEP7_JavaVMPP7_JNIEnvPv+208)
12-05 10:22:40.154 245-245/? A/DEBUG:     #22 pc 00000000001460fc  /system/lib64/libart.so (_ZN3art8CheckJII19AttachCurrentThreadEP7_JavaVMPP7_JNIEnvPv+124)
12-05 10:22:40.154 245-245/? A/DEBUG:     #23 pc 0000000000018f3c  /data/app/com.example.helloworld-2/lib/arm64/libwlmedia.so (_ZN10WlJavaCall11callPcmDataEiPv+96)
12-05 10:22:40.155 245-245/? A/DEBUG:     #24 pc 000000000001bc5c  /data/app/com.example.helloworld-2/lib/arm64/libwlmedia.so (_ZN7WlAudio10getPCMDataEv+612)
12-05 10:22:40.155 245-245/? A/DEBUG:     #25 pc 000000000001b92c  /data/app/com.example.helloworld-2/lib/arm64/libwlmedia.so (_Z17pcmBufferCallBackPKPK30SLAndroidSimpleBufferQueueItf_Pv+48)
12-05 10:22:40.155 245-245/? A/DEBUG:     #26 pc 000000000000da0c  /system/lib64/libwilhelm.so
12-05 10:22:40.155 245-245/? A/DEBUG:     #27 pc 00000000000a6b9c  /system/lib64/libmedia.so (_ZN7android10AudioTrack18processAudioBufferEv+1752)
12-05 10:22:40.155 245-245/? A/DEBUG:     #28 pc 00000000000a7abc  /system/lib64/libmedia.so (_ZN7android10AudioTrack16AudioTrackThread10threadLoopEv+272)
12-05 10:22:40.155 245-245/? A/DEBUG:     #29 pc 000000000001579c  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+208)
12-05 10:22:40.155 245-245/? A/DEBUG:     #30 pc 0000000000014fec  /system/lib64/libutils.so
12-05 10:22:40.155 245-245/? A/DEBUG:     #31 pc 00000000000674c4  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
12-05 10:22:40.155 245-245/? A/DEBUG:     #32 pc 000000000001c154  /system/lib64/libc.so (__start_thread+16)
12-05 10:22:40.435 245-245/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
12-05 10:22:40.436 245-245/? E/DEBUG: AM write failed: Broken pipe
12-05 10:22:40.480 549-567/? W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
12-05 10:22:40.501 549-571/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 60)
12-05 10:22:40.511 549-718/? W/ActivityManager: Force removing ActivityRecord{41d7e55 u0 com.example.helloworld/.HomeActivity t212}: app died, no saved state
12-05 10:22:40.724 694-694/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:763 android.content.ContextWrapper.sendBroadcast:397 com.android.internal.policy.PhoneWindow.boyueHighTextContrast:5449 com.android.internal.policy.PhoneWindow.boyueCustomOther:5393 com.android.internal.policy.PhoneWindow$DecorView.onWindowFocusChanged:3387 
12-05 10:22:40.735 549-716/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 4009 uid 10030

**Comment by wanliyang1990** [comment]
这个是空指针异常了 加我的QQ（596353036）吧 有问题好讨论
