### ISSUE TITLE
播放几次程序就超卡，崩了

### ISSUE THREAD

**Issue by kingtami** [wanliyang1990/wlmedia#14]
![image](https://user-images.githubusercontent.com/6318710/71058471-e9d5bb00-219a-11ea-998d-f981d3bc0b1c.png)
系统同事提供的图，大佬你看看能发现啥问题不？麻烦啦~

**Comment by wanliyang1990** [comment]
图片打不开呢

**Comment by wanliyang1990** [comment]
看到图片了 你这个用的不是最新更新的版本吧 最新的版本是有版本号结尾的 你升级一下试试呢

**Comment by jason609** [comment]
我也遇到这个问题了  用的是最新版本1.0.1  反复进入退出播放页面 几次过后程序就崩溃了

**Comment by wanliyang1990** [comment]
退出播放页面：先调用stop，然后在complete回调里面再finish。你们在测试一下呢

**Comment by wanliyang1990** [comment]
如果有视频，在complete回调里面还要调用release回收底层opengl资源，实例demo里面就有相关的逻辑。如果还有崩溃，就需要你们提供一个测试项目给我了。

**Comment by jason609** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午2:29
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"不忘本心"<1449301367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放几次程序就超卡，崩了 (#14)




退出播放页面：先调用stop，然后在complete回调里面再finish。你们在测试一下呢

**Comment by jason609** [comment]
好像是快速切换导致的问题  因为我是进入页面立马退出  切换的频率很快  是不是资源还没释放完毕

**Comment by wanliyang1990** [comment]
是的，要确保资源释放完了才退出页面才行，而资源释放完会走complete方法的

**Comment by jason609** [comment]
我进入后不会播放 &nbsp;是点击开始按钮播放，并且播放链接是假的，所以会回调onError(),这样的话 release()不会回调onComplete(),
这个我怎么保证资源是否释放完成呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午3:03
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"不忘本心"<1449301367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放几次程序就超卡，崩了 (#14)




是的，要确保资源释放完了才退出页面才行，而资源释放完会走complete方法的

**Comment by wanliyang1990** [comment]
如果连接是假的 那么到了error里面 就表示资源释放完了

**Comment by wanliyang1990** [comment]
如果是先走了error，那么在退出时可以直接release surface资源

**Comment by jason609** [comment]
是  wlMedia.onSurfaceDestroy() 这个方法吗？;

**Comment by wanliyang1990** [comment]
@Override
    public void onBackPressed() {
        exit = true;
        if(wlMedia.isPlay())
        {
            wlMedia.stop();
        }
        else
        {
            wlMedia.release();
            super.onBackPressed();
        }
    }

**Comment by jason609** [comment]
我是这样写的 &nbsp;跟你demo 里面的写法一致


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午3:30
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"不忘本心"<1449301367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放几次程序就超卡，崩了 (#14)




@override
 public void onBackPressed() {
 exit = true;
 if(wlMedia.isPlay())
 {
 wlMedia.stop();
 }
 else
 {
 wlMedia.release();
 super.onBackPressed();
 }
 }

**Comment by wanliyang1990** [comment]
还是会崩溃吗，给我一个测试项目吧

**Comment by kingtami** [comment]
> 看到图片了 你这个用的不是最新更新的版本吧 最新的版本是有版本号结尾的 你升级一下试试呢

好吧，现在是一套 start stop release 点完就崩了，怀疑可能跟机器有关系。非常感谢你的答复~项目很好，只是可惜稳定性不太适应我的机器，貌似替代品不好找哟~

**Comment by wanliyang1990** [comment]
能说一下你是什么机器不 我也很好奇呢

**Comment by jason609** [comment]
红米note5A,但应该跟机型关系不大，oppo手机也同样的问题。主要是反复快速进入退出，几次之后会崩溃。
我昨天在进入与退出时各加了50ms延迟后，没有崩溃了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 晚上11:34
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"不忘本心"<1449301367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放几次程序就超卡，崩了 (#14)




能说一下你是什么机器不 我也很好奇呢

**Comment by wanliyang1990** [comment]
麻烦给我写一个可以复现的demo呢，我这边能复现问题就能解决的

**Comment by jason609** [comment]
行 我等会给你写一个。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 上午9:29
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"不忘本心"<1449301367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放几次程序就超卡，崩了 (#14)




麻烦给我写一个可以复现的demo呢，我这边能复现问题就能解决的

**Comment by wanliyang1990** [comment]
好的 麻烦了

**Comment by jason609** [comment]
操作为：快速进入然后快速退出，反复操作，次数不固定，少则几次，多则二十几次，就会有崩溃的情况出现。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 上午9:31
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"不忘本心"<1449301367@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放几次程序就超卡，崩了 (#14)




好的 麻烦了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

TestPlayerDemo.zip (78.16M, 2020年01月18日 10:25 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7665643019077cc346f006664761531703515209510507091c550707054c550f54044909030051150401540353030401500105016173616c541610600d00185d4321015d0e4f1b51416559&t=exs_ftn_download&code=1ed0aaa8

**Comment by wanliyang1990** [comment]
好的

**Comment by wanliyang1990** [comment]
你把activity配置改成这样你再测试一下：
<activity android:name=".PlayerActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:launchMode="singleTask"></activity>

**Comment by wanliyang1990** [comment]
``<activity android:name=".PlayerActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:launchMode="singleTask"></activity>

**Comment by wanliyang1990** [comment]
怎样测试没，我这里用红米note5测试已经不崩溃了。

**Comment by wanliyang1990** [comment]
@kingtami 可以测试一下现在这个版本（1.0.6）吗， 我这边更改了底层的一下渲染逻辑，以前会崩溃的手机已经都不会崩溃了，不知道你的设备还会不？

**Comment by kingtami** [comment]
> @kingtami 可以测试一下现在这个版本（1.0.6）吗， 我这边更改了底层的一下渲染逻辑，以前会崩溃的手机已经都不会崩溃了，不知道你的设备还会不？

收到，我后续反馈结果哈。

**Comment by wanliyang1990** [comment]
好的 @kingtami
