### ISSUE TITLE
华为meta20和p30播放黑屏

### ISSUE THREAD

**Issue by pie-tk** [wanliyang1990/wlmedia#16]
系统更新到android10之后无法播放，右下角的水印有出现

**Comment by wanliyang1990** [comment]
好的知道了 我去找相关设备测试一下

**Comment by wanliyang1990** [comment]
我没有找到合适的测试机，我这边只找了一个magic2 10的系统测试可以播放，你可以加我的QQ（596353036），这样交流更方便

**Comment by wanliyang1990** [comment]
问题已定位：是用户buffer数据问题，播放器没问题！
