### ISSUE TITLE
更新后播放rtsp出现下半边模糊等问题

### ISSUE THREAD

**Issue by lyl15151865258** [wanliyang1990/wlmedia#17]
之前用的是implementation 'ywl.ywl5320:wlmedia:1.0.0-beta17'，这两天发现不能引用了，故更新到'ywl.ywl5320:wlmedia:1.0.4'，发现播放摄像头视频流出现下半部模糊（偶尔可能出现几秒钟的清晰画面），且视频无限卡顿，摄像头视频带有时间，时间基本都是跳跃性前进，希望作者查明一下问题。

**Comment by wanliyang1990** [comment]
好的 添加我的QQ（596353036）吧 具体描述一下你的问题

**Comment by wanliyang1990** [comment]
好的 添加我的QQ吧 具体描述一下你的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李玉亮"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 下午4:54
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wanliyang1990/wlmedia] 更新后播放rtsp出现下半边模糊等问题 (#17)




之前用的是implementation 'ywl.ywl5320:wlmedia:1.0.0-beta17'，这两天发现不能引用了，故更新到'ywl.ywl5320:wlmedia:1.0.4'，发现播放摄像头视频流出现下半部模糊（偶尔可能出现几秒钟的清晰画面），且视频无限卡顿，摄像头视频带有时间，时间基本都是跳跃性前进，希望作者查明一下问题。

**Comment by wanliyang1990** [comment]
播放rtsp流 ，设置播放模式为tcp防止丢帧
