### ISSUE TITLE
请问是否支持音频ADPCM解码，byte[]解码播放开始几秒黑屏

### ISSUE THREAD

**Issue by CrazyDoraemon** [wanliyang1990/wlmedia#19]
作者你好，请问是否支持音频ADPCM解码？
以及输入byte[]类型h264视频解码播放开始有几秒黑屏，出现画面时会很快的播放完刚才黑屏的那几秒画面，然后正常，并且由于通过TCP获取的h264视频流数据比较大导致播放一会就会开始频繁花屏。

**Comment by wanliyang1990** [comment]
你好

**Comment by CrazyDoraemon** [comment]
你好，传入ADPCM音频数据没有声音，是不支持ADPCM的解码吗？

**Comment by wanliyang1990** [comment]
现在是没有解码ADPCM这种数据的功能的哈，不过接下来的版本可以考虑添加进去，还有纯PCM数据播放等，好像现在很多都是g711*的音频。

**Comment by CrazyDoraemon** [comment]
好的，谢谢您的解答，我再研究一下
