### ISSUE TITLE
未start之前，wlMusic.getDuration()一直为0

### ISSUE THREAD

**Issue by hanxiaofeng** [wanliyang1990/wlmedia#2]
`         wlMusic.prePared();//准备开始

        Log.e("tag","duration = "+wlMusic.getDuration());

        wlMusic.setOnPreparedListener(new OnPreparedListener() {
            @Override
            public void onPrepared() {
                Log.e("tag","prepare duration = "+wlMusic.getDuration());
//                wlMusic.start(); //准备完成开始播放
            }
        });`

未开始播放之前，如何获取音频文件时长，这样获取一直为0

**Comment by wanliyang1990** [comment]
要获取duration必须在准备完成的回调（setOnPreparedListener）里面获取，此时才把数据解析完了的，是异步操作

**Comment by hanxiaofeng** [comment]
@wanliyang1990 我就是放在onPrepared回调里获取的，但是getDuration还是为0

**Comment by hanxiaofeng** [comment]
我用的是https://github.com/wanliyang1990/wlmusic    库：implementation 'ywl.ywl5320:libmusic:1.2.6'

**Comment by wanliyang1990** [comment]
你用wlmedia这个库试试呢

**Comment by hanxiaofeng** [comment]
@wanliyang1990 试了下wlmedia，时间可以获取到，但WlOnTimeInfoListener回调的当前时间会比duration少个两三秒，这个属于正常情况吗？

**Comment by wanliyang1990** [comment]
我底层是获取的音频和视频的最长时间值，回调的有可能单独是音频的时长，不过也算正常的，你可以先测试一下，有大问题的话我可以改一下底层逻辑。

**Comment by hanxiaofeng** [comment]
@wanliyang1990 我换了个音频地址，测试了下时间误差又很小了，和音频文件地址有关系？

**Comment by wanliyang1990** [comment]
是和音频或者视频文件有关，解析封装文件的时候，里面有时长属性，但是每个音频自己也有pts的属性，这2个值不一定完全相等，而现实的时间就是这个pts，音频的pts只有获取到了数据才知道，所以有一定误差是正常的

**Comment by hanxiaofeng** [comment]
@wanliyang1990 多谢
