### ISSUE TITLE
avformat_open_input

### ISSUE THREAD

**Issue by Nelson-KK** [wanliyang1990/wlmedia#20]
const char *dataSource = "http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8";

    AVFormatContext *avFormatContext;
 
   av_register_all();
    avcodec_register_all();
    avformat_network_init();

    int ret = avformat_open_input(&avFormatContext, dataSource, NULL, NULL);

通过android ndk 调用这段代码app直接崩溃了，想问一下可能是什么原因造成的，androidmanifest文件中已经申明了internet 权限

**Comment by wanliyang1990** [comment]
**首先你这个问题不在这个库的范围**
先确定崩溃的位置（https://blog.csdn.net/ywl5320/article/details/90581071），然后才能解决问题。不过你这几句话没毛病，所以怀疑是其他问题引起的。
