### ISSUE TITLE
缓冲时间总是和当前时间差7秒

### ISSUE THREAD

**Issue by zhaichuankai** [wanliyang1990/wlmedia#24]
打印发现缓冲时间总是和当前时间差7秒， 能设置缓冲策略吗

**Comment by wanliyang1990** [comment]
现在是底层设置了一个最大队列数 上层还不能更改

**Comment by wanliyang1990** [comment]
底层缓冲时间加了策略了有 队列大小、时间和内存大小3个策略 如：wlMedia.setBufferSize(WlBufferType.BUFFER_TIME, 30); 缓冲30s
