### ISSUE TITLE
SDK 代码有打算开源吗

### ISSUE THREAD

**Issue by yibaimishenlan** [wanliyang1990/wlmedia#26]
首先膜拜下大神。
ijkplayer 和 exoplayer 学习成本有点大，老哥愿意把SDK的代码开源嘛，希望老哥把SDK 的代码开源，让我们学习下大神的精髓。

**Comment by wanliyang1990** [comment]
目前还不会开源的哈，如果要学习里面的知识，可以看我的视频课程，readme最后面有课程链接
