### ISSUE TITLE
demo没有水印，使用库有水印，水印怎么去除？

### ISSUE THREAD

**Issue by qiaoxiao** [wanliyang1990/wlmedia#27]

**Comment by wanliyang1990** [comment]
无水印版需要根据包名定制才行哈

**Comment by qiaoxiao** [comment]
定制的费用？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wanliyang1990/wlmedia"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 晚上9:53
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"XiaoJoe"<4390583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] demo没有水印，使用库有水印，水印怎么去除？ (#27)





 
无水印版需要根据包名定制才行哈

**Comment by wanliyang1990** [comment]
那你加我QQ（596353036）吧

**Comment by qiaoxiao** [comment]
我只是测试了一下，我暂时 还用不上，哪天用了你的wlmedia库 联系你！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ywl5320"<notifications@github.com&gt;; 
发送时间: 2020年8月12日(星期三) 晚上10:03
收件人: "wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;; 
抄送: "XiaoJoe"<4390583@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wanliyang1990/wlmedia] demo没有水印，使用库有水印，水印怎么去除？ (#27)





 
那你加我QQ（596353036）吧

**Comment by ManBali** [comment]
定制得花钱？

**Comment by wanliyang1990** [comment]
要去水印 是收费的
