### ISSUE TITLE
播放视频为什么没声音？

### ISSUE THREAD

**Issue by Lightning627** [wanliyang1990/wlmedia#31]
`class MainActivity : AppCompatActivity() {

    private val wlMedia = WlMedia()
    private val TAG = "MKV播放器"
    private val url = "http://10.55.52.32:8080/xjzw_cut.mkv"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        wlMedia.source = url
        wlMedia.setSourceType(WlSourceType.NORMAL)
        wlMedia.setCodecType(WlCodecType.CODEC_MEDIACODEC)//设置解码模式（默认硬解码
        wlMedia.setPlayModel(WlPlayModel.PLAYMODEL_ONLY_VIDEO)
        wlMedia.setOnPreparedListener {
            Log.i(TAG, "播放器准备好了")
            wlMedia.start()
//            wlMedia.setMute()
            wlMedia.setAudioChannel(0)
        }

        wlMedia.setOnCompleteListener {
            when (it) {
                WlComplete.WL_COMPLETE_HANDLE -> {

                }
            }
        }
        wlMedia.setOnErrorListener { code, msg ->
            Log.e(TAG, "错误码=$code : $msg")
        }
        player.setWlMedia(wlMedia)
        player.setOnVideoViewListener(object : WlOnVideoViewListener {
            override fun moveRight(value: Double, move_type: Int) {
                Log.i(TAG, "$value  $move_type")
            }

            override fun moveLeft(value: Double, move_type: Int) {

            }

            override fun onDoubleClick() {

            }

            override fun moveX(value: Double, move_type: Int) {

            }

            override fun initSuccess() {
                wlMedia.prepared()
            }

            override fun onSingleClick() {
                Log.i(TAG, "音轨 = ${wlMedia.audioChannels}")
                Log.i(TAG, "字幕 = ${wlMedia.subTitleChannels}")
            }
        })
    }

    override fun onDestroy() {
        wlMedia.exit()
        super.onDestroy()
    }
}`

**Comment by wanliyang1990** [comment]
播放模式你设置的只播放视频哦：wlMedia.setPlayModel(WlPlayModel.PLAYMODEL_ONLY_VIDEO) 改一下这里

**Comment by Lightning627** [comment]
谢谢，搞定了。。
