### ISSUE TITLE
播放H.264编码的byte[]视频

### ISSUE THREAD

**Issue by dashifuguye** [wanliyang1990/wlmedia#32]
你好，Android端接收到H.264编码的视频，一帧一帧byte[]数据，想用你的这个库进行实时播放，应该怎样用呀？像图片里这样直接返回byte[]数据就可以吗？我按照sample中WlBufferActivity.java的写法做了，但是显示不出来，报的错误是“can not open the url”，请问该怎样解决  

![image](https://user-images.githubusercontent.com/21324724/101711430-7ffea180-3ace-11eb-9ae1-49739d9f28ff.png)

**Comment by wanliyang1990** [comment]
回调里面是返回数据源的（播放器主动调用），你这样是不行的，可以用队列来缓存接收到的byte[]数据，然后在回调里面按顺序返回就行

**Comment by dashifuguye** [comment]
我仿照sample中WlBufferActivity.java的写法，刚进去缓存队列还没有数据，就已经返回了13次空的byte[]，然后就是onError: can not open the url，然后就onComplete，结束了，此时我在往缓存队列里加数据，视频也不会再播放了，这个过程中一直黑屏；另外我尝试了收到视频数据后再调用 wlMedia.start()，但是也是一直黑屏，求解

**Comment by wanliyang1990** [comment]
注意：回调里面如果返回了null就表明结束了，所以当开始时没有数据时，可以阻塞在回调里面，等有了数据再返回。类似于生产者消费者模型。

**Comment by dashifuguye** [comment]
哦哦，好的，我再试试，回复这么快，感谢

**Comment by dashifuguye** [comment]
我使用LinkedBlockingQueue来保存视频数据，回调里返回videoDataQueue.take()，但还是无法显示视频，onError返回 can not open the url，请问这是怎么回事？

**Comment by wanliyang1990** [comment]
可以把回调里面的数据保存到文件中，然后测试一下是否可以播放。如果还有疑问加我QQ（596353036）

**Comment by dashifuguye** [comment]
好的，我试试，谢谢
