### ISSUE TITLE
请问怎样播放加密视频呢？

### ISSUE THREAD

**Issue by TYUpya** [wanliyang1990/wlmedia#33]
请问怎样播放加密视频呢？需求是服务器给一个加密的视频的url，App端调用你的SDK传入url进行播放。但是App端解密逻辑要写在哪里呢？请问有Demo吗？

**Comment by wanliyang1990** [comment]
目前实现的加密视频是本地视频，流这种形式没有包含。

**Comment by TYUpya** [comment]
好的，抱歉打扰了。
