### ISSUE TITLE
播放网路的url音频，6002错误

### ISSUE THREAD

**Issue by yinyekai** [wanliyang1990/wlmedia#34]
onError: 6002
onComplete: WL_COMPLETE_ERROR
我之前用wlmusic可以正常播放音频，这个就不行……是同一个音频地址

**Comment by yinyekai** [comment]
我是进入activity初始化，然后就报这个错了

**Comment by wanliyang1990** [comment]
error里面具体什么错呢

**Comment by yinyekai** [comment]
具体错误忘记打印了，后来我换成1.1.5就好了……




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wanliyang1990/wlmedia"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 凌晨0:41
收件人:&nbsp;"wanliyang1990/wlmedia"<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;"尹业凯"<578615061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmedia] 播放网路的url音频，6002错误 (#34)





 
error里面具体什么错呢

**Comment by wanliyang1990** [comment]
可以了就好
