### ISSUE TITLE
支持rtp吗？

### ISSUE THREAD

**Issue by xiaomao1** [wanliyang1990/wlmedia#35]
wlMedia.setSource 一个rtp的地址，并没有播放出来，rtsp的倒是可以，这是什么情况呀？

**Comment by wanliyang1990** [comment]
有测试地址么 发我测试一下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;xiaomao1&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月19日(星期二) 上午9:06
收件人:&nbsp;&quot;wanliyang1990/wlmedia&quot;<wlmedia@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wanliyang1990/wlmedia] 支持rtp吗？ (#35)
