### ISSUE TITLE
soundtouch播放会有杂音

### ISSUE THREAD

**Issue by Code-Lonely** [wanliyang1990/wlmedia#41]
作者你好，我看了你的这个视频https://download.csdn.net/course/detail/6842
成功把soundtouch移植到了安卓上
我现在想做一个跟你类似的播放器。我使用了javacv中的ffmpeg组件，将音频进行解码获取了pcm数据，然后使用AudioTrack对象进行pcm数据的播放。中间我也想加入变调变速的功能，但是在使用过程中，我的音频是双声道的，我将soundtouch也设置成了双声道，但是播放出来的声音会有杂音，如果我将soundtouch设置成单声道就不会有这个问题，但同时降调之后会有轻微的嗡嗡声，我不知道这个是javacv中的ffmpeng问题，还是我移植soundtouch的方式不对，但我可以确定，音频是没有问题的，因为我使用你的wlmedia去进行播放，没有任何问题。

下面是我的示例代码
![image](https://user-images.githubusercontent.com/60993027/176578101-55c9234b-c088-4f9f-bb8e-a668aa958f58.png)
![image](https://user-images.githubusercontent.com/60993027/176578139-344928c5-c312-4fa5-b2a6-923264394d0f.png)

你能告诉我这是什么问题导致的吗

**Comment by wanliyang1990** [comment]
最简单的验证方法就是把送入audiotrack的pcm数据保存为文件，然后看一下这个pcm是不是有问题，这样一步一步的确定问题在哪里
