### ISSUE TITLE
支持实时分贝获取？

### ISSUE THREAD

**Issue by Veryed-VS** [wanliyang1990/wlmedia#42]
我试了进行音频播放。实际上WlOnPcmDataListener回调的数据。
public void onPcmData(int i, byte[] bytes, double v)

这个参数V就是实时分贝，但是实际上它永远在60左右跳动。根本不是与音乐节奏对上。
请问是这个不支持实时分贝检测还是我使用错了？

**Comment by wanliyang1990** [comment]
后面我测一下这个哈，你也可以自己根据bytes来计算分贝。
