### ISSUE TITLE
您好，播放大华摄像头的视频流黑屏，请问有什么办法吗

### ISSUE THREAD

**Issue by liuwenzhi1** [wanliyang1990/wlmedia#46]
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)

**Comment by wanliyang1990** [comment]
你好，看这个错误是硬解码抛出异常了，你切换到软解码试试呢

**Comment by liuwenzhi1** [comment]
软解码可以，但是有花屏的现象

**Comment by liuwenzhi1** [comment]
请问有什么方式解决吗

**Comment by liuwenzhi1** [comment]
用其他的不会，我用的是自己内网的大华摄像头进行测试的
