### ISSUE TITLE
还会更新so库吗

### ISSUE THREAD

**Issue by zhoucarson** [wanliyang1990/wlmedia#47]
支持最新的av1解码吗

**Comment by wanliyang1990** [comment]
最新版本已经支持 av1了，不过还在内测中：
<img width="880" alt="image" src="https://github.com/wanliyang1990/wlmedia/assets/10057444/379c96e8-94dd-4d87-b739-a71771efb8f9">

**Comment by wanliyang1990** [comment]
3.0.0新版本已发布，av1已经支持了
