### ISSUE TITLE
code is :1001, msg is :can not open the url

### ISSUE THREAD

**Issue by mimishen** [wanliyang1990/wlmedia#5]
code is :1001, msg is :can not open the url:

 http://www.ytmp3.cn/down/57799.mp3

这个音频地址打不开呢？？

**Comment by wanliyang1990** [comment]
这个音频地址可以打开的。你检查一下你的网络权限打开没有，还有9.0手机默认屏蔽了http连接，只能https。

**Comment by mimishen** [comment]
都试了，打不开呀，，，
code is :1001, msg is :can not open the url: http://www.ytmp3.cn/down/57799.mp3

**Comment by wanliyang1990** [comment]
那应该是你哪里弄错了，可以加我的QQ（596353036）我看看怎么回事。

**Comment by mimishen** [comment]
加了，，
