### ISSUE TITLE
RSTP 流 解密播放

### ISSUE THREAD

**Issue by hujinhuahjh** [wanliyang1990/wlmedia#54]
大佬你好，请问一下怎样播放加密 rtsp 流
can not open the url: rtsp://**:**@192.168.*.*:554/stream1 (Permission denied)

**Comment by ywl5320** [comment]
是有用户名和密码这种格式的吗

**Comment by ywl5320** [comment]
播放形式如下:
rtsp://username:password@192.168.31.111:8089/h264/avstream/...

**Comment by ywl5320** [comment]
同一个网络环境下，你用ffmpeg测试一下呢。还有其他网络视频能播放不？

**Comment by ywl5320** [comment]
好的，ffmpeg播放rtsp的优化参数都可以用的，使用setoptions来设置
