### ISSUE TITLE
请问一下作者，是如何支持rtp\udp这些协议的

### ISSUE THREAD

**Issue by diswy** [wanliyang1990/wlmedia#7]
编译了ijk，开启了rtp\udp但是无法播放，使用大佬的这个可以播放udp://  和 rtp:// 。大佬可以指点一下么？是ijk就是不支持么，或者大佬的课程里面有讲这些内容不

**Comment by wanliyang1990** [comment]
主要是设置打开流的时候 把协议写上，ffmpeg有一个字典序，里面添加av_dict_set(&options, "rtsp_transport", "tcp/udp", 0)，这样就可以了。有兴趣可以看一下我的课程哦
