### ISSUE TITLE
老哥，请问怎么降低rtsp的延时？

### ISSUE THREAD

**Issue by leestars** [wanliyang1990/wlmedia#9]

**Comment by wanliyang1990** [comment]
首先是rtsp的源头要控制好时间
播放器端的话：
1、第一减少播放器内部缓存帧
2、根据自己rtsp的编码格式，直接创建相应解码器，减少探测时间
还有rtsp数据的gop大小要不要太大等等

**Comment by li-fei** [comment]
你们这个库rstp延时大概时间是多少？

**Comment by wanliyang1990** [comment]
> 你们这个库rstp延时大概时间是多少？

延迟还是比较低的，你可以自己试一下
